; keys definition

; ::Send, {U+} ;HANGUL CHOSEONG

;g::Send, {U+1100} ;HANGUL CHOSEONG KIYEOK
;k::Send, {U+1101} ;HANGUL CHOSEONG SSANGKIYEOK

;n::Send, {U+1102} ;HANGUL CHOSEONG NIEUN

;d::Send, {U+1103} ;HANGUL CHOSEONG TIKEUT
;t::Send, {U+1104} ;HANGUL CHOSEONG SSANGTIKEUT

;r::Send, {U+1105} ;HANGUL CHOSEONG RIEUL

;m::Send, {U+1106} ;HANGUL CHOSEONG MIEUM

;b::Send, {U+1107} ;HANGUL CHOSEONG PIEUP
;p::Send, {U+1108} ;HANGUL CHOSEONG SSANGPIEUP

;z::Send, {U+1109} ;HANGUL CHOSEONG SIOS
;s::Send, {U+110A} ;HANGUL CHOSEONG SSANGSIOS

;x::Send, {U+110B} ;HANGUL CHOSEONG IEUNG

;v::Send, {U+110C} ;HANGUL CHOSEONG CIEUC
;f::Send, {U+110D} ;HANGUL CHOSEONG SSANGCIEUC

;c::Send, {U+110E} ;HANGUL CHOSEONG CHIEUCH
;q::Send, {U+110F} ;HANGUL CHOSEONG KHIYEOKH
;j::Send, {U+1110} ;HANGUL CHOSEONG THIEUTH
;w::Send, {U+1111} ;HANGUL CHOSEONG PHIEUPH
;h::Send, {U+1112} ;HANGUL CHOSEONG HIEUH


; ::Send, {U+} ;HANGUL JUNGSEONG

;1::Send, {U+1160} ;HANGUL JUNGSEONG FILLER

;a::Send, {U+1161} ;HANGUL JUNGSEONG A
;+e::Send, {U+1162} ;HANGUL JUNGSEONG AE

;::Send, {U+1163} ;HANGUL JUNGSEONG YA
;::Send, {U+1164} ;HANGUL JUNGSEONG YAE

;::Send, {U+1165} ;HANGUL JUNGSEONG EO
;::Send, {U+1166} ;HANGUL JUNGSEONG E

;::Send, {U+1167} ;HANGUL JUNGSEONG YEO
;::Send, {U+1168} ;HANGUL JUNGSEONG YE

;::Send, {U+1169} ;HANGUL JUNGSEONG O

;::Send, {U+116A} ;HANGUL JUNGSEONG WA
;::Send, {U+116B} ;HANGUL JUNGSEONG WAE

;::Send, {U+116C} ;HANGUL JUNGSEONG OE
;::Send, {U+116D} ;HANGUL JUNGSEONG YO

;::Send, {U+116E} ;HANGUL JUNGSEONG U

;::Send, {U+116F} ;HANGUL JUNGSEONG WEO
;::Send, {U+1170} ;HANGUL JUNGSEONG WE
;::Send, {U+1171} ;HANGUL JUNGSEONG WI

;::Send, {U+1172} ;HANGUL JUNGSEONG YU
;::Send, {U+1173} ;HANGUL JUNGSEONG EU

;::Send, {U+1174} ;HANGUL JUNGSEONG YI
;::Send, {U+1175} ;HANGUL JUNGSEONG I


;::Send, {U+} ;HANGUL JONGSEONG

;::Send, {U+11A8} ;HANGUL JONGSEONG KIYEOK
;::Send, {U+11A9} ;HANGUL JONGSEONG SSANGKIYEOK
;::Send, {U+11AA} ;HANGUL JONGSEONG KIYEOK-SIOS

;::Send, {U+11AB} ;HANGUL JONGSEONG NIEUN
;::Send, {U+11AC} ;HANGUL JONGSEONG NIEUN-CIEUC
;::Send, {U+11AD} ;HANGUL JONGSEONG NIEUN-HIEUH

;::Send, {U+11AE} ;HANGUL JONGSEONG TIKEUT

;::Send, {U+11AF} ;HANGUL JONGSEONG RIEUL
;::Send, {U+11B0} ;HANGUL JONGSEONG RIEUL-KIYEOK
;::Send, {U+11B1} ;HANGUL JONGSEONG RIEUL-MIEUM
;::Send, {U+11B2} ;HANGUL JONGSEONG RIEUL-PIEUP
;::Send, {U+11B3} ;HANGUL JONGSEONG RIEUL-SIOS
;::Send, {U+11B4} ;HANGUL JONGSEONG RIEUL-THIEUTH
;::Send, {U+11B5} ;HANGUL JONGSEONG RIEUL-PHIEUPH
;::Send, {U+11B6} ;HANGUL JONGSEONG RIEUL-HIEUH

;::Send, {U+11B7} ;HANGUL JONGSEONG MIEUM

;::Send, {U+11B8} ;HANGUL JONGSEONG PIEUP
;::Send, {U+11B9} ;HANGUL JONGSEONG PIEUPSIOS

;::Send, {U+11BA} ;HANGUL JONGSEONG SIOS
;::Send, {U+11BB} ;HANGUL JONGSEONG SSANGSIOS

;::Send, {U+11BC} ;HANGUL JONGSEONG IEUNG

;::Send, {U+11BD} ;HANGUL JONGSEONG CIEUC

;::Send, {U+11BE} ;HANGUL JONGSEONG CHIEUCH
;::Send, {U+11BF} ;HANGUL JONGSEONG KHIEUKH
;::Send, {U+11C0} ;HANGUL JONGSEONG THIEUTH
;::Send, {U+11C1} ;HANGUL JONGSEONG PHIEUPH
;::Send, {U+11C2} ;HANGUL JONGSEONG HIEUH



MsgBox, OnInputVar %v_output%
